### ISSUE TITLE
Update FAQ

### ISSUE THREAD

**Issue by aaron-em** [benrady/shinatra#6] opened 2016-11-14 17:49 UTC
Out of date documentation. Works fine under Cygwin. Example:

![shinatra cygwin](https://cloud.githubusercontent.com/assets/5650970/20276046/abba1dfe-aa68-11e6-9ea8-6b915e2dc0ee.PNG)

**Comment by skibz** [comment] 2016-11-23 10:21
i figured this would work just fine under cygwin or even the windows subsystem for linux

**Comment by benrady** [comment] 2016-11-27 16:21
Duplicate of #2

**Closed by benrady** 2016-11-27 16:21 UTC
